# Generated by Django 4.2.6 on 2023-10-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cocina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
