# Generated by Django 4.2.6 on 2023-10-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cocina', '0005_alter_receta_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(null=True, upload_to='recetas'),
        ),
    ]
