# Generated by Django 4.2.6 on 2023-10-31 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cocina', '0006_receta_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='codigo',
            new_name='id',
        ),
    ]
