# Generated by Django 4.2.6 on 2023-10-31 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cocina', '0008_rename_nombre_receta_nombre_receta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='dificultad',
            new_name='calificacion',
        ),
    ]
